### ISSUE TITLE
No such file or directory: 'config/default/adminGuiConfig.json'

### ISSUE THREAD

**Issue by Carli99** [qwc-services/qwc-admin-gui#5]
After i run 'python server.py' on http://localhost:5031 I have message 'FileNotFoundError: [Errno 2] No such file or directory: 'config/default/adminGuiConfig.json''.
How to insert this file?

**Comment by pka** [comment]
This should be solved with the current docker-compose-example.yml. Could you try again, please?

**Comment by AndreasAtakan** [comment]
Having the same issue with *qwc-docker*.
Logs: [logs.txt](https://github.com/qwc-services/qwc-admin-gui/files/4742649/logs.txt)
NGINX error:

![Skjermbilde_2020-06-07_20-10-48](https://user-images.githubusercontent.com/45392631/83976571-00173500-a8fb-11ea-8a04-064ca686cab5.png)

**Comment by pka** [comment]
Can try again after updating all docker containers with `docker-compose pull`

**Comment by AndreasAtakan** [comment]
@pka Still the same error after updating containers with `docker-compose pull`
[logs.txt](https://github.com/qwc-services/qwc-admin-gui/files/4746382/logs.txt)

**Comment by HusseinKabbout** [comment]
@Carli99 For the service to run, it requires a file called `adminGuiConfig.json`. Look at [this](https://github.com/qwc-services/qwc-admin-gui#configuration) for more information on how to create this file and where to save it.

@AndreasAtakan I have freshly cloned the `qwc-docker` repository and didn't get the error message. Please try again and make sure you also do a `git pull` in the `qwc-docker` directory.

**Comment by AndreasAtakan** [comment]
@HusseinKabbout fixed now.
It turned out the error was in my postgres config. No errors in qwc-docker.
Many thanks for the help!

**Comment by HusseinKabbout** [comment]
I will close this issue, because all the needed instructions were given. @Carli99  If the problem still persists after reading the documentation, then please reopen this issue.
